version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build-and-test:
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm install
                      - run: npm test
    build-and-deploy:
        docker:
            - image: circleci/node:7.10
        steps:
            - checkout
            - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP -p $DROPLET_PORT "/home/admin/circleci/deploy_project.sh"
workflows:
    build-and-test:
        jobs:
            - build-and-test
    build-and-deploy:
        jobs:
            - build-and-test
                filters:
                    branches:
                        only:
                            - master
            - build-and-deploy
                  filters:
                      branches:
                          only:
                              - master
